import { readdirSync, readFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

const tauriRoot = new URL("../../src-tauri/", import.meta.url);
const commandListPath = new URL("src/app_commands.rs", tauriRoot);
const buildScriptPath = new URL("build.rs", tauriRoot);
const cargoLockPath = new URL("Cargo.lock", tauriRoot);
const libraryPath = new URL("src/lib.rs", tauriRoot);
const tauriConfigPath = new URL("tauri.conf.json", tauriRoot);
const androidFileProviderPathsPath = new URL(
  "gen/android/app/src/main/res/xml/file_paths.xml",
  tauriRoot,
);
const capabilitiesPath = new URL("capabilities/", tauriRoot);
const capabilityPath = new URL("capabilities/default.json", tauriRoot);
const permissionsPath = new URL("permissions/autogenerated/", tauriRoot);

const expectedCommands = [
  "ack_stream",
  "cancel_stream",
  "get_stream_snapshot",
  "host_broker_probe_count",
  "host_broker_request",
  "register_host_broker_session",
  "release_stream",
  "rotate_host_broker_session",
  "start_mock_stream",
  "wait_stream_terminal",
];

const retiredRawCommands = [
  "privileged_probe",
  "privileged_probe_count",
  "sanitize_plugin_html",
];

const expectedCapabilityPermissions = expectedCommands
  .map((command) => `allow-${command.replaceAll("_", "-")}`)
  .sort();

/**
 * @param {string} source
 * @param {"allow" | "deny"} key
 * @returns {string[] | null}
 */
function tomlCommandArray(source, key) {
  const match = source.match(new RegExp(`^commands\\.${key} = \\[([^\\n]*)\\]$`, "m"));
  if (match === null) return null;
  return [...match[1].matchAll(/"([a-z][a-z0-9_]*)"/g)].map(
    (commandMatch) => commandMatch[1],
  );
}

function declaredCommands() {
  const source = readFileSync(commandListPath, "utf8");
  return [...source.matchAll(/^\s{12}([a-z][a-z0-9_]*)[,]$/gm)]
    .map((match) => match[1])
    .sort();
}

/**
 * @param {string} lock
 * @param {string} packageName
 * @returns {string | null}
 */
function lockedPackageVersion(lock, packageName) {
  const escapedName = packageName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return (
    lock.match(
      new RegExp(
        `\\[\\[package\\]\\]\\nname = "${escapedName}"\\nversion = "([^"]+)"`,
      ),
    )?.[1] ?? null
  );
}

describe("Tauri command surface", () => {
  it("scopes Android FileProvider grants to purpose-specific app-owned directories", () => {
    const paths = readFileSync(androidFileProviderPathsPath, "utf8");
    const policy = paths.replace(/<!--[\s\S]*?-->/g, "");
    const policyBody = policy.match(/<paths\b[^>]*>([\s\S]*?)<\/paths>/)?.[1];
    expect(policyBody).toBeDefined();
    const mappings = [
      ...(policyBody ?? "").matchAll(
        /<([a-z][a-z0-9-]*)\b([^>]*)\/?>/g,
      ),
    ].map(([, element, attributes]) => ({
      element,
      name: attributes.match(/\bname="([^"]+)"/)?.[1],
      path: attributes.match(/\bpath="([^"]+)"/)?.[1],
    }));

    expect(mappings).toEqual([
      { element: "files-path", name: "exports", path: "exports/" },
      { element: "cache-path", name: "share_cache", path: "share/" },
      {
        element: "external-files-path",
        name: "media_exports",
        path: "LorePia/Exports/",
      },
    ]);
    expect(policy).not.toMatch(/<(?:external-path|root-path)\b/);
    expect(mappings.every((mapping) => mapping.path !== ".")).toBe(true);
  });

  it("pins the audited Tauri Channel implementation", () => {
    const lock = readFileSync(cargoLockPath, "utf8");
    expect(lockedPackageVersion(lock, "tauri")).toBe("2.11.5");
    expect(lockedPackageVersion(lock, "tauri-runtime-wry")).toBe("2.11.4");

    const library = readFileSync(libraryPath, "utf8");
    expect(library).toContain(
      "const TAURI_CHANNEL_JSON_DIRECT_THRESHOLD_BYTES: usize = 8_192;",
    );
    expect(library).toContain(
      "const LOREPIA_DIRECT_JSON_BUDGET_BYTES: usize = 4_096;",
    );
  });

  it("uses one exact command list for the build manifest and invoke handler", () => {
    expect(declaredCommands()).toEqual(expectedCommands);

    const buildScript = readFileSync(buildScriptPath, "utf8");
    const library = readFileSync(libraryPath, "utf8");
    expect(buildScript).toContain(
      "const APP_COMMANDS: &[&str] = with_lorepia_app_commands!(command_names);",
    );
    expect(buildScript).toContain("AppManifest::new().commands(APP_COMMANDS)");
    expect(library).toContain(
      ".invoke_handler(with_lorepia_app_commands!(generate_lorepia_handler))",
    );
  });

  it("keeps the capability allowlist equal to the shared command list", () => {
    /** @type {{ identifier: string, webviews: string[], permissions: string[] }} */
    const capability = JSON.parse(readFileSync(capabilityPath, "utf8"));
    expect(
      readdirSync(capabilitiesPath).filter((name) => name.endsWith(".json")),
    ).toEqual(["default.json"]);
    expect(capability.identifier).toBe("default");
    expect(capability.webviews).toEqual(["main"]);
    expect(capability).not.toHaveProperty("windows");
    expect(capability).not.toHaveProperty("remote");
    expect([...capability.permissions].sort()).toEqual(
      expectedCapabilityPermissions,
    );
    expect(
      capability.permissions.every(
        (permission) => !permission.includes("*") && permission !== "core:default",
      ),
    ).toBe(true);

    const tauriConfig = JSON.parse(readFileSync(tauriConfigPath, "utf8"));
    expect(tauriConfig.app.security.capabilities).toEqual(["default"]);
  });

  it("keeps generated app permissions equal to the shared command list", () => {
    const generatedCommands = readdirSync(permissionsPath)
      .filter((name) => name.endsWith(".toml"))
      .map((name) => name.slice(0, -".toml".length))
      .sort();

    expect(generatedCommands).toEqual(expectedCommands);
    for (const command of expectedCommands) {
      const source = readFileSync(
        new URL(`permissions/autogenerated/${command}.toml`, tauriRoot),
        "utf8",
      );
      expect(source.match(/^\[\[permission\]\]$/gm)).toHaveLength(2);
      expect(tomlCommandArray(source, "allow")).toEqual([command]);
      expect(tomlCommandArray(source, "deny")).toEqual([command]);
      expect(source).toContain(
        `identifier = "allow-${command.replaceAll("_", "-")}"`,
      );
      expect(source).toContain(
        `identifier = "deny-${command.replaceAll("_", "-")}"`,
      );
    }
  });

  it("does not reintroduce a retired raw command wrapper", () => {
    const rustSources = readdirSync(new URL("src/", tauriRoot))
      .filter((name) => name.endsWith(".rs"))
      .map((name) => readFileSync(new URL(`src/${name}`, tauriRoot), "utf8"))
      .join("\n");

    for (const command of retiredRawCommands) {
      expect(declaredCommands()).not.toContain(command);
      expect(rustSources).not.toMatch(
        new RegExp(`#\\[tauri::command\\][\\s\\S]{0,256}fn\\s+${command}\\b`),
      );
    }
  });
});
