import { readdirSync, readFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

const tauriRoot = new URL("../../src-tauri/", import.meta.url);
const commandListPath = new URL("src/app_commands.rs", tauriRoot);
const buildScriptPath = new URL("build.rs", tauriRoot);
const libraryPath = new URL("src/lib.rs", tauriRoot);
const capabilityPath = new URL("capabilities/default.json", tauriRoot);
const permissionsPath = new URL("permissions/autogenerated/", tauriRoot);

const expectedCommands = [
  "ack_stream",
  "cancel_stream",
  "get_stream_snapshot",
  "host_broker_probe_count",
  "host_broker_request",
  "register_host_broker_session",
  "rotate_host_broker_session",
  "start_mock_stream",
];

const retiredRawCommands = [
  "privileged_probe",
  "privileged_probe_count",
  "sanitize_plugin_html",
];

const expectedCapabilityPermissions = expectedCommands
  .map((command) => `allow-${command.replaceAll("_", "-")}`)
  .sort();

/**
 * @param {string} source
 * @param {"allow" | "deny"} key
 * @returns {string[] | null}
 */
function tomlCommandArray(source, key) {
  const match = source.match(new RegExp(`^commands\\.${key} = \\[([^\\n]*)\\]$`, "m"));
  if (match === null) return null;
  return [...match[1].matchAll(/"([a-z][a-z0-9_]*)"/g)].map(
    (commandMatch) => commandMatch[1],
  );
}

function declaredCommands() {
  const source = readFileSync(commandListPath, "utf8");
  return [...source.matchAll(/^\s{12}([a-z][a-z0-9_]*)[,]$/gm)]
    .map((match) => match[1])
    .sort();
}

describe("Tauri command surface", () => {
  it("uses one exact command list for the build manifest and invoke handler", () => {
    expect(declaredCommands()).toEqual(expectedCommands);

    const buildScript = readFileSync(buildScriptPath, "utf8");
    const library = readFileSync(libraryPath, "utf8");
    expect(buildScript).toContain(
      "const APP_COMMANDS: &[&str] = with_lorepia_app_commands!(command_names);",
    );
    expect(buildScript).toContain("AppManifest::new().commands(APP_COMMANDS)");
    expect(library).toContain(
      ".invoke_handler(with_lorepia_app_commands!(generate_lorepia_handler))",
    );
  });

  it("keeps the capability allowlist equal to the shared command list", () => {
    /** @type {{ permissions: string[] }} */
    const capability = JSON.parse(readFileSync(capabilityPath, "utf8"));
    expect([...capability.permissions].sort()).toEqual(
      expectedCapabilityPermissions,
    );
  });

  it("keeps generated app permissions equal to the shared command list", () => {
    const generatedCommands = readdirSync(permissionsPath)
      .filter((name) => name.endsWith(".toml"))
      .map((name) => name.slice(0, -".toml".length))
      .sort();

    expect(generatedCommands).toEqual(expectedCommands);
    for (const command of expectedCommands) {
      const source = readFileSync(
        new URL(`permissions/autogenerated/${command}.toml`, tauriRoot),
        "utf8",
      );
      expect(source.match(/^\[\[permission\]\]$/gm)).toHaveLength(2);
      expect(tomlCommandArray(source, "allow")).toEqual([command]);
      expect(tomlCommandArray(source, "deny")).toEqual([command]);
      expect(source).toContain(
        `identifier = "allow-${command.replaceAll("_", "-")}"`,
      );
      expect(source).toContain(
        `identifier = "deny-${command.replaceAll("_", "-")}"`,
      );
    }
  });

  it("does not reintroduce a retired raw command wrapper", () => {
    const rustSources = readdirSync(new URL("src/", tauriRoot))
      .filter((name) => name.endsWith(".rs"))
      .map((name) => readFileSync(new URL(`src/${name}`, tauriRoot), "utf8"))
      .join("\n");

    for (const command of retiredRawCommands) {
      expect(declaredCommands()).not.toContain(command);
      expect(rustSources).not.toMatch(
        new RegExp(`#\\[tauri::command\\][\\s\\S]{0,256}fn\\s+${command}\\b`),
      );
    }
  });
});
